title: Lucas SALAND
description: Data Science student
site_title: '@LucasSLD - Lucas SALAND'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: LucasSLD
blog_url: 
email: lucas.saland@centrale.centralelille.fr
keybase_username: 
twitter_username: 
reddit_username: 

# absolute or relative
profile_picture: assets/images/pp.png

# Google Analytics ID
google_analytics: 